[pytest]

markers=
    sanity: It is for exection of Sanity test
    api: It is for exection of API test
    regression: It is for exection of regression test
    database: It is for exection of Database test